/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ArrayOfDouble {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ArrayOfDouble(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArrayOfDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ArrayOfDouble obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mdvJNI.delete_ArrayOfDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArrayOfDouble(int size) {
    this(mdvJNI.new_ArrayOfDouble(size), true);
  }

  public double get(long idx) {
    return mdvJNI.ArrayOfDouble_get(swigCPtr, this, idx);
  }

  public void set(long idx, double value) {
    mdvJNI.ArrayOfDouble_set(swigCPtr, this, idx, value);
  }

}
