/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class BitSet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BitSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BitSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(BitSet obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mdvJNI.delete_BitSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BitSet(long size) {
    this(mdvJNI.new_BitSet(size), true);
  }

  public boolean set(long pos) {
    return mdvJNI.BitSet_set(swigCPtr, this, pos);
  }

  public void reset(long pos) {
    mdvJNI.BitSet_reset(swigCPtr, this, pos);
  }

  public boolean test(long pos) {
    return mdvJNI.BitSet_test(swigCPtr, this, pos);
  }

  public void fill(boolean val) {
    mdvJNI.BitSet_fill(swigCPtr, this, val);
  }

  public long size() {
    return mdvJNI.BitSet_size(swigCPtr, this);
  }

  public long count(boolean val) {
    return mdvJNI.BitSet_count(swigCPtr, this, val);
  }

  public long capacity() {
    return mdvJNI.BitSet_capacity(swigCPtr, this);
  }

}
