/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ClientConnectionConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ClientConnectionConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClientConnectionConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ClientConnectionConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mdvJNI.delete_ClientConnectionConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTimeout(long value) {
    mdvJNI.ClientConnectionConfig_timeout_set(swigCPtr, this, value);
  }

  public long getTimeout() {
    return mdvJNI.ClientConnectionConfig_timeout_get(swigCPtr, this);
  }

  public void setKeepidle(long value) {
    mdvJNI.ClientConnectionConfig_keepidle_set(swigCPtr, this, value);
  }

  public long getKeepidle() {
    return mdvJNI.ClientConnectionConfig_keepidle_get(swigCPtr, this);
  }

  public void setKeepcnt(long value) {
    mdvJNI.ClientConnectionConfig_keepcnt_set(swigCPtr, this, value);
  }

  public long getKeepcnt() {
    return mdvJNI.ClientConnectionConfig_keepcnt_get(swigCPtr, this);
  }

  public void setKeepintvl(long value) {
    mdvJNI.ClientConnectionConfig_keepintvl_set(swigCPtr, this, value);
  }

  public long getKeepintvl() {
    return mdvJNI.ClientConnectionConfig_keepintvl_get(swigCPtr, this);
  }

  public long getRetryInterval() {
    return mdvJNI.ClientConnectionConfig_getRetryInterval(swigCPtr, this);
  }

  public long getResponseTimeout() {
    return mdvJNI.ClientConnectionConfig_getResponseTimeout(swigCPtr, this);
  }

  public void setRetryInterval(long v) {
    mdvJNI.ClientConnectionConfig_setRetryInterval(swigCPtr, this, v);
  }

  public void setResponseTimeout(long v) {
    mdvJNI.ClientConnectionConfig_setResponseTimeout(swigCPtr, this, v);
  }

  public ClientConnectionConfig() {
    this(mdvJNI.new_ClientConnectionConfig(), true);
  }

}
