/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ClientConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ClientConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClientConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ClientConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mdvJNI.delete_ClientConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ClientConfig(String addr) {
    this(mdvJNI.new_ClientConfig(addr), true);
  }

  public void setDb(ClientDbConfig value) {
    mdvJNI.ClientConfig_db_set(swigCPtr, this, ClientDbConfig.getCPtr(value), value);
  }

  public ClientDbConfig getDb() {
    long cPtr = mdvJNI.ClientConfig_db_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ClientDbConfig(cPtr, false);
  }

  public void setConnection(ClientConnectionConfig value) {
    mdvJNI.ClientConfig_connection_set(swigCPtr, this, ClientConnectionConfig.getCPtr(value), value);
  }

  public ClientConnectionConfig getConnection() {
    long cPtr = mdvJNI.ClientConfig_connection_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ClientConnectionConfig(cPtr, false);
  }

  public void setThreadpool(ClientThreadpoolConfig value) {
    mdvJNI.ClientConfig_threadpool_set(swigCPtr, this, ClientThreadpoolConfig.getCPtr(value), value);
  }

  public ClientThreadpoolConfig getThreadpool() {
    long cPtr = mdvJNI.ClientConfig_threadpool_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ClientThreadpoolConfig(cPtr, false);
  }

}
