/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Client {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Client(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Client obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Client obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public static Client connect(ClientConfig config) {
    long cPtr = mdvJNI.Client_connect(ClientConfig.getCPtr(config), config);
    return (cPtr == 0) ? null : new Client(cPtr, false);
  }

  public void close() {
    mdvJNI.Client_close(swigCPtr, this);
  }

  public Table createTable(TableDesc table) {
    long cPtr = mdvJNI.Client_createTable(swigCPtr, this, TableDesc.getCPtr(table), table);
    return (cPtr == 0) ? null : new Table(cPtr, true);
  }

  public Table getTable(UUID uuid) {
    long cPtr = mdvJNI.Client_getTable(swigCPtr, this, UUID.getCPtr(uuid), uuid);
    return (cPtr == 0) ? null : new Table(cPtr, true);
  }

  public boolean insert(RowSet rowset) {
    return mdvJNI.Client_insert(swigCPtr, this, RowSet.getCPtr(rowset), rowset);
  }

  public RowSet mdv_client_select_impl(Table table, BitSet fields, String filter) {
    long cPtr = mdvJNI.Client_mdv_client_select_impl(swigCPtr, this, Table.getCPtr(table), table, BitSet.getCPtr(fields), fields, filter);
    return (cPtr == 0) ? null : new RowSet(cPtr, true);
  }

}
