/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class FieldType {
  public final static FieldType MDV_FLD_TYPE_BOOL = new FieldType("MDV_FLD_TYPE_BOOL", mdvJNI.MDV_FLD_TYPE_BOOL_get());
  public final static FieldType MDV_FLD_TYPE_CHAR = new FieldType("MDV_FLD_TYPE_CHAR", mdvJNI.MDV_FLD_TYPE_CHAR_get());
  public final static FieldType MDV_FLD_TYPE_BYTE = new FieldType("MDV_FLD_TYPE_BYTE", mdvJNI.MDV_FLD_TYPE_BYTE_get());
  public final static FieldType MDV_FLD_TYPE_INT8 = new FieldType("MDV_FLD_TYPE_INT8", mdvJNI.MDV_FLD_TYPE_INT8_get());
  public final static FieldType MDV_FLD_TYPE_UINT8 = new FieldType("MDV_FLD_TYPE_UINT8", mdvJNI.MDV_FLD_TYPE_UINT8_get());
  public final static FieldType MDV_FLD_TYPE_INT16 = new FieldType("MDV_FLD_TYPE_INT16", mdvJNI.MDV_FLD_TYPE_INT16_get());
  public final static FieldType MDV_FLD_TYPE_UINT16 = new FieldType("MDV_FLD_TYPE_UINT16", mdvJNI.MDV_FLD_TYPE_UINT16_get());
  public final static FieldType MDV_FLD_TYPE_INT32 = new FieldType("MDV_FLD_TYPE_INT32", mdvJNI.MDV_FLD_TYPE_INT32_get());
  public final static FieldType MDV_FLD_TYPE_UINT32 = new FieldType("MDV_FLD_TYPE_UINT32", mdvJNI.MDV_FLD_TYPE_UINT32_get());
  public final static FieldType MDV_FLD_TYPE_INT64 = new FieldType("MDV_FLD_TYPE_INT64", mdvJNI.MDV_FLD_TYPE_INT64_get());
  public final static FieldType MDV_FLD_TYPE_UINT64 = new FieldType("MDV_FLD_TYPE_UINT64", mdvJNI.MDV_FLD_TYPE_UINT64_get());
  public final static FieldType MDV_FLD_TYPE_FLOAT = new FieldType("MDV_FLD_TYPE_FLOAT", mdvJNI.MDV_FLD_TYPE_FLOAT_get());
  public final static FieldType MDV_FLD_TYPE_DOUBLE = new FieldType("MDV_FLD_TYPE_DOUBLE", mdvJNI.MDV_FLD_TYPE_DOUBLE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FieldType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FieldType.class + " with value " + swigValue);
  }

  private FieldType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FieldType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FieldType(String swigName, FieldType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FieldType[] swigValues = { MDV_FLD_TYPE_BOOL, MDV_FLD_TYPE_CHAR, MDV_FLD_TYPE_BYTE, MDV_FLD_TYPE_INT8, MDV_FLD_TYPE_UINT8, MDV_FLD_TYPE_INT16, MDV_FLD_TYPE_UINT16, MDV_FLD_TYPE_INT32, MDV_FLD_TYPE_UINT32, MDV_FLD_TYPE_INT64, MDV_FLD_TYPE_UINT64, MDV_FLD_TYPE_FLOAT, MDV_FLD_TYPE_DOUBLE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

