/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class mdv {
  public static long fieldTypeSize(FieldType t) {
    return mdvJNI.fieldTypeSize(t.swigValue());
  }

  public static boolean clientInitialize() {
    return mdvJNI.clientInitialize();
  }

  public static void clientFinalize() {
    mdvJNI.clientFinalize();
  }

}
