/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ObjectId {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ObjectId(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectId obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ObjectId obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mdvJNI.delete_ObjectId(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setU8(SWIGTYPE_p_unsigned_char value) {
    mdvJNI.ObjectId_u8_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getU8() {
    long cPtr = mdvJNI.ObjectId_u8_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setNode(long value) {
    mdvJNI.ObjectId_node_set(swigCPtr, this, value);
  }

  public long getNode() {
    return mdvJNI.ObjectId_node_get(swigCPtr, this);
  }

  public void setId(java.math.BigInteger value) {
    mdvJNI.ObjectId_id_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getId() {
    return mdvJNI.ObjectId_id_get(swigCPtr, this);
  }

  public ObjectId() {
    this(mdvJNI.new_ObjectId(), true);
  }

  public String toString() {
    return mdvJNI.ObjectId_toString(swigCPtr, this);
  }

}
