/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Row {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Row(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Row obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Row obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mdvJNI.delete_Row(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Row(long size) {
    this(mdvJNI.new_Row(size), true);
  }

  public long cols() {
    return mdvJNI.Row_cols(swigCPtr, this);
  }

  public long fieldSize(long idx) {
    return mdvJNI.Row_fieldSize(swigCPtr, this, idx);
  }

  public FieldType fieldType(long idx) {
    return FieldType.swigToEnum(mdvJNI.Row_fieldType(swigCPtr, this, idx));
  }

  public boolean getBool(long idx) {
    return mdvJNI.Row_getBool(swigCPtr, this, idx);
  }

  public ArrayOfBool getBoolArray(long idx) {
    long cPtr = mdvJNI.Row_getBoolArray(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new ArrayOfBool(cPtr, false);
  }

  public char getChar(long idx) {
    return mdvJNI.Row_getChar(swigCPtr, this, idx);
  }

  public ArrayOfChar getCharArray(long idx) {
    long cPtr = mdvJNI.Row_getCharArray(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new ArrayOfChar(cPtr, false);
  }

  public String getString(long idx) {
    return mdvJNI.Row_getString(swigCPtr, this, idx);
  }

  public short getByte(long idx) {
    return mdvJNI.Row_getByte(swigCPtr, this, idx);
  }

  public ArrayOfByte getByteArray(long idx) {
    long cPtr = mdvJNI.Row_getByteArray(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new ArrayOfByte(cPtr, false);
  }

  public short getUint8(long idx) {
    return mdvJNI.Row_getUint8(swigCPtr, this, idx);
  }

  public ArrayOfUint8 getUint8Array(long idx) {
    long cPtr = mdvJNI.Row_getUint8Array(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new ArrayOfUint8(cPtr, false);
  }

  public byte getInt8(long idx) {
    return mdvJNI.Row_getInt8(swigCPtr, this, idx);
  }

  public ArrayOfInt8 getInt8Array(long idx) {
    long cPtr = mdvJNI.Row_getInt8Array(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new ArrayOfInt8(cPtr, false);
  }

  public int getUint16(long idx) {
    return mdvJNI.Row_getUint16(swigCPtr, this, idx);
  }

  public ArrayOfUint16 getUint16Array(long idx) {
    long cPtr = mdvJNI.Row_getUint16Array(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new ArrayOfUint16(cPtr, false);
  }

  public short getInt16(long idx) {
    return mdvJNI.Row_getInt16(swigCPtr, this, idx);
  }

  public ArrayOfInt16 getInt16Array(long idx) {
    long cPtr = mdvJNI.Row_getInt16Array(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new ArrayOfInt16(cPtr, false);
  }

  public long getUint32(long idx) {
    return mdvJNI.Row_getUint32(swigCPtr, this, idx);
  }

  public ArrayOfUint32 getUint32Array(long idx) {
    long cPtr = mdvJNI.Row_getUint32Array(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new ArrayOfUint32(cPtr, false);
  }

  public int getInt32(long idx) {
    return mdvJNI.Row_getInt32(swigCPtr, this, idx);
  }

  public ArrayOfInt32 getInt32Array(long idx) {
    long cPtr = mdvJNI.Row_getInt32Array(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new ArrayOfInt32(cPtr, false);
  }

  public java.math.BigInteger getUint64(long idx) {
    return mdvJNI.Row_getUint64(swigCPtr, this, idx);
  }

  public ArrayOfUint64 getUint64Array(long idx) {
    long cPtr = mdvJNI.Row_getUint64Array(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new ArrayOfUint64(cPtr, false);
  }

  public long getInt64(long idx) {
    return mdvJNI.Row_getInt64(swigCPtr, this, idx);
  }

  public ArrayOfInt64 getInt64Array(long idx) {
    long cPtr = mdvJNI.Row_getInt64Array(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new ArrayOfInt64(cPtr, false);
  }

  public float getFloat(long idx) {
    return mdvJNI.Row_getFloat(swigCPtr, this, idx);
  }

  public ArrayOfFloat getFloatArray(long idx) {
    long cPtr = mdvJNI.Row_getFloatArray(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new ArrayOfFloat(cPtr, false);
  }

  public double getDouble(long idx) {
    return mdvJNI.Row_getDouble(swigCPtr, this, idx);
  }

  public ArrayOfDouble getDoubleArray(long idx) {
    long cPtr = mdvJNI.Row_getDoubleArray(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new ArrayOfDouble(cPtr, false);
  }

  public boolean setBool(long idx, boolean val) {
    return mdvJNI.Row_setBool(swigCPtr, this, idx, val);
  }

  public boolean setBoolArray(long idx, ArrayOfBool arr, long size) {
    return mdvJNI.Row_setBoolArray(swigCPtr, this, idx, ArrayOfBool.getCPtr(arr), arr, size);
  }

  public boolean setChar(long idx, char val) {
    return mdvJNI.Row_setChar(swigCPtr, this, idx, val);
  }

  public boolean setCharArray(long idx, ArrayOfChar arr, long size) {
    return mdvJNI.Row_setCharArray(swigCPtr, this, idx, ArrayOfChar.getCPtr(arr), arr, size);
  }

  public boolean setString(long idx, String str) {
    return mdvJNI.Row_setString(swigCPtr, this, idx, str);
  }

  public boolean setByte(long idx, short val) {
    return mdvJNI.Row_setByte(swigCPtr, this, idx, val);
  }

  public boolean setByteArray(long idx, ArrayOfByte arr, long size) {
    return mdvJNI.Row_setByteArray(swigCPtr, this, idx, ArrayOfByte.getCPtr(arr), arr, size);
  }

  public boolean setUint8(long idx, short val) {
    return mdvJNI.Row_setUint8(swigCPtr, this, idx, val);
  }

  public boolean setUint8Array(long idx, ArrayOfUint8 arr, long size) {
    return mdvJNI.Row_setUint8Array(swigCPtr, this, idx, ArrayOfUint8.getCPtr(arr), arr, size);
  }

  public boolean setInt8(long idx, byte val) {
    return mdvJNI.Row_setInt8(swigCPtr, this, idx, val);
  }

  public boolean setInt8Array(long idx, ArrayOfInt8 arr, long size) {
    return mdvJNI.Row_setInt8Array(swigCPtr, this, idx, ArrayOfInt8.getCPtr(arr), arr, size);
  }

  public boolean setUint16(long idx, int val) {
    return mdvJNI.Row_setUint16(swigCPtr, this, idx, val);
  }

  public boolean setUint16Array(long idx, ArrayOfUint16 arr, long size) {
    return mdvJNI.Row_setUint16Array(swigCPtr, this, idx, ArrayOfUint16.getCPtr(arr), arr, size);
  }

  public boolean setInt16(long idx, short val) {
    return mdvJNI.Row_setInt16(swigCPtr, this, idx, val);
  }

  public boolean setInt16Array(long idx, ArrayOfInt16 arr, long size) {
    return mdvJNI.Row_setInt16Array(swigCPtr, this, idx, ArrayOfInt16.getCPtr(arr), arr, size);
  }

  public boolean setUint32(long idx, long val) {
    return mdvJNI.Row_setUint32(swigCPtr, this, idx, val);
  }

  public boolean setUint32Array(long idx, ArrayOfUint32 arr, long size) {
    return mdvJNI.Row_setUint32Array(swigCPtr, this, idx, ArrayOfUint32.getCPtr(arr), arr, size);
  }

  public boolean setInt32(long idx, int val) {
    return mdvJNI.Row_setInt32(swigCPtr, this, idx, val);
  }

  public boolean setInt32Array(long idx, ArrayOfInt32 arr, long size) {
    return mdvJNI.Row_setInt32Array(swigCPtr, this, idx, ArrayOfInt32.getCPtr(arr), arr, size);
  }

  public boolean setUint64(long idx, java.math.BigInteger val) {
    return mdvJNI.Row_setUint64(swigCPtr, this, idx, val);
  }

  public boolean setUint64Array(long idx, ArrayOfUint64 arr, long size) {
    return mdvJNI.Row_setUint64Array(swigCPtr, this, idx, ArrayOfUint64.getCPtr(arr), arr, size);
  }

  public boolean setInt64(long idx, long val) {
    return mdvJNI.Row_setInt64(swigCPtr, this, idx, val);
  }

  public boolean setInt64Array(long idx, ArrayOfInt64 arr, long size) {
    return mdvJNI.Row_setInt64Array(swigCPtr, this, idx, ArrayOfInt64.getCPtr(arr), arr, size);
  }

  public boolean setFloat(long idx, float val) {
    return mdvJNI.Row_setFloat(swigCPtr, this, idx, val);
  }

  public boolean setFloatArray(long idx, ArrayOfFloat arr, long size) {
    return mdvJNI.Row_setFloatArray(swigCPtr, this, idx, ArrayOfFloat.getCPtr(arr), arr, size);
  }

  public boolean setDouble(long idx, double val) {
    return mdvJNI.Row_setDouble(swigCPtr, this, idx, val);
  }

  public boolean setDoubleArray(long idx, ArrayOfDouble arr, long size) {
    return mdvJNI.Row_setDoubleArray(swigCPtr, this, idx, ArrayOfDouble.getCPtr(arr), arr, size);
  }

}
