/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class RowSet {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RowSet(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RowSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RowSet obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mdvJNI.delete_RowSet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RowSet(Table table) {
    this(mdvJNI.new_RowSet(Table.getCPtr(table), table), true);
  }

  public boolean add(Row row) {
    return mdvJNI.RowSet_add(swigCPtr, this, Row.getCPtr(row), row);
  }

  public RowSetEnumerator enumerator() {
    long cPtr = mdvJNI.RowSet_enumerator(swigCPtr, this);
    return (cPtr == 0) ? null : new RowSetEnumerator(cPtr, true);
  }

}
