/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


import java.util.Iterator;

public class RowSetEnumerator implements Iterator<Row>, AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RowSetEnumerator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RowSetEnumerator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RowSetEnumerator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public void close() {
    mdvJNI.RowSetEnumerator_close(swigCPtr, this);
  }

  public boolean hasNext() {
    return mdvJNI.RowSetEnumerator_hasNext(swigCPtr, this);
  }

  public Row next() {
    long cPtr = mdvJNI.RowSetEnumerator_next(swigCPtr, this);
    return (cPtr == 0) ? null : new Row(cPtr, false);
  }

  public void remove() {
    mdvJNI.RowSetEnumerator_remove(swigCPtr, this);
  }

  public boolean reset() {
    return mdvJNI.RowSetEnumerator_reset(swigCPtr, this);
  }

  public boolean moveNext() {
    return mdvJNI.RowSetEnumerator_moveNext(swigCPtr, this);
  }

  public Row current() {
    long cPtr = mdvJNI.RowSetEnumerator_current(swigCPtr, this);
    return (cPtr == 0) ? null : new Row(cPtr, true);
  }

  public ObjectId row_id() {
    return new ObjectId(mdvJNI.RowSetEnumerator_row_id(swigCPtr, this), true);
  }

}
