/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TableDesc {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TableDesc(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TableDesc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TableDesc obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mdvJNI.delete_TableDesc(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TableDesc(String tableName) {
    this(mdvJNI.new_TableDesc(tableName), true);
  }

  public boolean addField(FieldType type, long limit, String name) {
    return mdvJNI.TableDesc_addField(swigCPtr, this, type.swigValue(), limit, name);
  }

}
