#MDV service Dockerfile


FROM debian:buster-20200607-slim
LABEL MAINTAINER="Nikolay ILYIN <ni@peerf.me>"
LABEL name="mdv"

RUN apt-get update -q -q \
&& apt-get upgrade --yes \
&& apt-get install -yq apt-utils \
&& apt-get install -yq --no-install-recommends \
           systemd sudo less \
&& apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/

COPY medveddb_1.0.0.deb .
RUN apt-get install -yq ./medveddb_1.0.0.deb

LABEL version="1.0"

COPY medved.conf ./medveddb/

# change to the user, created by installing the package medveddb
RUN chown -R medved:medved /opt
#USER medved

# Espose default MDV port
EXPOSE 4800

# Add VOLUMEs to allow backup of config, logs and databases
VOLUME ["/opt/data"]

# Finally launch medveddb service.
ENTRYPOINT ["/opt/medveddb/medved", "--cfg=/opt/medveddb/medved.conf"]
